<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['egress_firewall_allow_all'] = 'Разрешить все';
$lang['egress_firewall_allow_all_and_specify_block_destinations'] = 'Разрешить весь исходящий трафик - указать блочные пункты назначения';
$lang['egress_firewall_app_description'] = 'Приложение "Брандмауэр" позволяет вам блокировать определенные виды трафика через вашу сеть.';
$lang['egress_firewall_app_name'] = 'Выходной Брандмауэр';
$lang['egress_firewall_block_all'] = 'Блокировать все';
$lang['egress_firewall_destination_domains'] = 'Целевые домены';
$lang['egress_firewall_destination_ports'] = 'Порт (ы) назначения';
$lang['egress_firewall_mode'] = 'Режим';
$lang['egress_firewall_web_lang_block_all_and_specify_allow_destinations'] = 'Блокировать весь исходящий трафик - указать разрешенные направления';
