<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['egress_firewall_allow_all'] = 'Tillåt alla';
$lang['egress_firewall_allow_all_and_specify_block_destinations'] = 'Tillåt all utgående trafik - specificera blockerade mål';
$lang['egress_firewall_app_description'] = 'Egressappen gör så att du kan blockera viss trafik från ditt nätverk.';
$lang['egress_firewall_app_name'] = 'Egress brandväggen';
$lang['egress_firewall_block_all'] = 'Blockera alla';
$lang['egress_firewall_destination_domains'] = 'Destinationsdomäner';
$lang['egress_firewall_destination_ports'] = 'Målport(ar)';
$lang['egress_firewall_mode'] = 'Mod';
$lang['egress_firewall_web_lang_block_all_and_specify_allow_destinations'] = 'Blockera all utgående trafik - ange tillåtna mål';
