<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['egress_firewall_allow_all'] = 'Zezwól na wszystko';
$lang['egress_firewall_allow_all_and_specify_block_destinations'] = 'Zezwól na cały ruch wychodzący - określ blokowane miejsca docelowe';
$lang['egress_firewall_app_description'] = 'Aplikacja Firewall wyjścia pozwala na blokowanie konkretnych rodzajów ruchu przed wyjściem z Twojej sieci.';
$lang['egress_firewall_app_name'] = 'Firewall wyjścia';
$lang['egress_firewall_block_all'] = 'Zablokuj wszystko';
$lang['egress_firewall_destination_domains'] = 'Domeny docelowe';
$lang['egress_firewall_destination_ports'] = 'Port(y) docelowe';
$lang['egress_firewall_mode'] = 'Tryb';
$lang['egress_firewall_web_lang_block_all_and_specify_allow_destinations'] = 'Blokuj cały ruch wychodzący - określ dozwolone miejsca docelowe';
